### ISSUE TITLE
Hello! How to generate the predicted scores to calculate the metrics?

### ISSUE THREAD

**Issue by Leez-chestnut** [lllllllllllll-llll/SROCC_PLCC_calculate#1]
Thanks for the code! I am flesh here, for what I want to ask is that I have the model trained before but I do not know how to calculate the SROCC and PLCC, can you tell me how to use the code in details?

**Comment by lllllllllllll-llll** [comment]
Hello! This is the code used to compute cross database test for SROCC and PLCC. For example, given an IQA model trained on LIVE database, we use this model to calculate all the image scores on CSIQ database, then we put all these scores to a txt file. In addition, we put the ground truth scores to another txt file, and then, we can run calculate.m to calculate the SROCC and PLCC.

**Comment by Leez-chestnut** [comment]
Thanks
